return {
    Namespace = "tcainrework",
    Name = "Tainted Cain Rework",
    Items = [[
    collectible
    heart
    half_heart
    soul_heart
    half_soul_heart
    black_heart
    eternal_heart
    blended_heart
    bone_heart
    rotten_heart
    golden_heart
    penny
    nickel
    dime
    lucky_penny
    golden_penny
    key
    golden_key
    charged_key
    bomb
    golden_bomb
    giga_bomb
    mini_battery
    battery
    mega_battery
    golden_battery
    tarot_card
    reverse_tarot_card
    mtg_card
    holy_card
    credit_card
    card_against_humanity
    wild_card
    pill
    golden_pill
    rune
    rune_shard
    soul_stone
    dice_shard
    cracked_key
    eden_essence
    poop
    poop_block
    wooden_doll
    repentogon
    card
    ]]
}
